#ifndef POM_ARM_CONSTANTS_H
#define POM_ARM_CONSTANTS_H

#define POM_ARM_SERVO_PORT 0
#define POM_ARM_SWEEP_LEFT_POSITION 300
#define POM_ARM_SWEEP_RIGHT_POSITION 1700
#define POM_ARM_STOW_POSITION 1024
#define POM_ARM_SWEEP_PAUSE_MS 300

#endif
